version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgis/postgis:15-3.3  # Imagen oficial con PostGIS ya instalado
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_taxi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=empresataxi
    ports:
      - "5432:5432"  # Opcional: solo si quieres acceder a la DB desde fuera del VPS
    restart: always

  # Servicio de API (FastAPI)
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin_taxi:1234@db:5432/empresataxi
      - SECRET_KEY=cambia_esto_por_una_clave_segura_de_al_menos_32_caracteres
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=production
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: